version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    working_dir: /app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    working_dir: /app
    command: poetry run streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - backend
