[theme]
primaryColor = "#7F5AF0"         # Purple-blue accent (Anthropic-style)
backgroundColor = "#FFFFFF"      # Clean white background
secondaryBackgroundColor = "#F5F5F5"  # Light gray panel background
textColor = "#1F1F1F"            # Dark gray text
font = "sans serif"              # Clean, readable font
